[build]
  publish = ".output/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  API_BASE_URL = "https://your-backend-url.com/api"

[context.deploy-preview.environment]
  API_BASE_URL = "https://your-backend-url.com/api" 